In [76]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error,r2_score



In [10]:
cd D:/Fingertips_Shalini/Desktop/Data Files

D:\Fingertips_Shalini\Desktop\Data Files


In [16]:
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [18]:
df.experience=df.experience.fillna(0)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [25]:
import math
mean_test_score = math.floor(df['test_score(out of 10)'].mean())
mean_test_score

7

In [27]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(mean_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [28]:
regression_model = LinearRegression() 

In [30]:
regression_model.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [52]:
salary=df['salary($)']
salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [55]:
new_df=df.drop('salary($)',axis='columns')
new_df

experience  test_score(out of 10)  interview_score(out of 10)
0         0.0                    8.0                           9
1         0.0                    8.0                           6
2         5.0                    6.0                           7
3         2.0                   10.0                          10
4         7.0                    9.0                           6
5         3.0                    7.0                          10
6        10.0                    7.0                           7
7        11.0                    7.0                           8

In [36]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [56]:
regression_model.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [57]:
regression_model.fit(new_df,salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [59]:
salary_predicted_1=regression_model.predict([[2,9,6]])
salary_predicted_1

array([ 53713.86677124])

In [58]:
salary_predicted_2=regression_model.predict([[12,10,10]])
salary_predicted_2

array([ 93747.79628651])

In [60]:
salary_predicted=regression_model.predict(new_df)
salary_predicted

array([ 52090.46734071,  45648.01964161,  57964.2290839 ,  64525.1061363 ,
        68325.21184635,  60783.44785255,  74796.8832586 ,  79866.63483999])

In [64]:
rmse=mean_squared_error(salary,salary_predicted)
r2 = r2_score(salary,salary_predicted) 

In [65]:
print('Slope:' ,regression_model.coef_) 
print('Intercept:', regression_model.intercept_) 
print('Root mean squared error: ', rmse) 
print('R2 score: ', r2) 

Slope: [ 2922.26901502  2221.30909959  2147.48256637]
Intercept: 14992.6514467
Root mean squared error:  2660640.90979
R2 score:  0.977013901427


# y=m1x1+m2x2+m3x3+b

In [66]:
2922.26901502*0 +2221.30909959*8+2147.48256637*9 +14992.6514467


52090.46734075

In [74]:
regression_model.

<bound method RegressorMixin.score of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)>

In [78]:
regression_model.score(new_df,salary_predicted)

1.0